- name: Configure Docker on EC2 Instances
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Docker login to Docker Hub
      shell: echo '{{ docker_password }}' | docker login -u '{{ docker_username }}' --password-stdin
      args:
        warn: false

    - name: Deploy Docker Container
      shell: docker run -dit --name finance-app -p 8084:8081 {{ docker_username }}/finance-me:1.0
      args:
        warn: false
