---
- name: Configure Docker and deploy finance-app container
  hosts: all
  become: true

  vars:
    docker_image_name: "nandini20/finance-app"
    docker_image_tag: "15"
    container_name: "finance-app"
    container_port_host: "8084"
    container_port_container: "8081"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Log into Docker Hub
      ansible.builtin.shell: |
        echo "{{ docker_password }}" | docker login -u "{{ docker_username }}" --password-stdin
      no_log: true

    - name: Pull Docker image
      community.docker.docker_image:
        name: "{{ docker_image_name }}"
        tag: "{{ docker_image_tag }}"
        source: pull

    - name: Run Docker container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image_name }}:{{ docker_image_tag }}"
        state: started
        restart_policy: always
        ports:
          - "{{ container_port_host }}:{{ container_port_container }}"

